### ISSUE TITLE
Clean BAM is larger than raw BAM files

### ISSUE THREAD

**Issue by zhaowsong** [stjude/XenoCP#42]
"Hi authors,

Thank you for your software. I am currently using xenocp to filter out mouse contamination from PDX WGS data. However, I have encountered some issues.

Firstly, the cleaned BAM file is larger than the original BAM file, and when I use samtools to count the lines, the cleaned BAM has more lines than the raw BAM.
<img width="791" alt="image" src="https://github.com/stjude/XenoCP/assets/116059475/36e9b1b8-ba84-499c-b0ee-546b5b152d05">
<img width="727" alt="image" src="https://github.com/stjude/XenoCP/assets/116059475/d3e4b986-3065-4b51-912a-49850e367d00">

Secondly, I am curious as my result files, SJOS013768_X3.sorted.xenocp.bam and SJOS013768_X3.sorted.xenocp.tie.bam, seem to be the same. In the example data, tie.bam is split into many files. Therefore, I would like to confirm if my output is correct.

Thirdly, how should I calculate the percentage of mouse contamination reads in the original BAM file?

Thank you."

**Comment by zhaowsong** [comment]
Additionally, I would like to inquire whether BWA mem should be used for WGS data. Currently, I am using BWA aln

**Comment by mcrusch** [comment]
From the screenshot, it appears to me that the cleansed BAM has slightly _fewer_ records, but slightly _greater_ size.  Assuming I am reading that correctly, that matches expectations.  When XenoCP identifies a mouse read, it marks the primary alignment as unmapped (so no change to record count), but it also discards any secondary alignments (reduces read count), as secondary alignments don't make sense for an unmapped read.  So, assuming there are secondary alignments in the input file, a slight decrease in read count is to be expected.

File sizes can slightly increase due to changes in the compressibility of the data.  Coordinate sorted data is generally more compressible as you have a lot of repeated sequence in proximity to each other.  By unmapping the read pairs, they move to the unmapped reads at the end of the file, meaning they are mixed in with reads with different sequence, leading to decreased compressibility.  There are other factors like the compression level used in generating the original BAM vs internal to XenoCP.  In general, it's hard to predict the output file size, but my expectation is that it would be similar to the input file size, which it appears to be in this case.

We made a change along the way to produce a single tie BAM.  However, that tie BAM looks way too big.  So, I'm going to need to look into this some more.  I will also check on the example to make sure it aligns with the current behavior.

I need to step away, but I will get back to you on the other questions.

**Comment by mcrusch** [comment]
To calculate the percent of reads identified as contaminating, you would take the difference in the number of primary mapped reads between the input and output BAM, and divide that by the number of reads (not records--so use primary total reads).

Regarding bwa aln vs mem...  I don't believe we have done an evaluation on this, but my assumption would be that you'd want to match the alignment method used within XenoCP to the one originally used for mapping the BAM.  The method relies on comparing the original alignment to the human reference to the XenoCP mapping to the target reference.  Using different methods for alignment would confound the comparison.  However, in practice, we don't have data to prove that matching the methods is the best approach.

**Comment by mcrusch** [comment]
Work tasks on this issue:

- [ ] Why is the tie BAM so large?
- [ ] Check the example to ensure it conforms with a single tie bam

**Comment by zhaowsong** [comment]
Dear Dr. mcrusch
I would like to express my gratitude for your previous explanation, which has been very helpful. However, I seem to have encountered a new issue, and I am wondering if there is a way to limit the memory usage of Xenocp.

I am using Singularity to run Xenocp with a request for 30 cores and 240GB of memory. Unfortunately, for some large WGS BAM files, the execution fails due to memory issues. Below, you'll find the relevant code snippet and the error message.

<img width="521" alt="image" src="https://github.com/stjude/XenoCP/assets/116059475/e336d7b6-4497-421b-b439-adc44d4282a2">
<img width="779" alt="image" src="https://github.com/stjude/XenoCP/assets/116059475/60ca9a08-0d19-4c81-b77e-b1590f92dced">

<img width="840" alt="image" src="https://github.com/stjude/XenoCP/assets/116059475/d43e2734-74df-447b-be6f-bb38734ac61f">

Best regards,
Zhao

**Comment by zhaowsong** [comment]
> To calculate the percent of reads identified as contaminating, you would take the difference in the number of primary mapped reads between the input and output BAM, and divide that by the number of reads (not records--so use primary total reads).
> 
> Regarding bwa aln vs mem... I don't believe we have done an evaluation on this, but my assumption would be that you'd want to match the alignment method used within XenoCP to the one originally used for mapping the BAM. The method relies on comparing the original alignment to the human reference to the XenoCP mapping to the target reference. Using different methods for alignment would confound the comparison. However, in practice, we don't have data to prove that matching the methods is the best approach.


Hello Dr. McRusch,

Regarding the calculation of contaminating reads, I'd like to confirm if my understanding is correct. Below is the flagstat.txt information for example input and output BAM files.
<img width="607" alt="image" src="https://github.com/stjude/XenoCP/assets/116059475/d309d258-08d4-4c6a-9d8e-6c6004954fde">

<img width="666" alt="image" src="https://github.com/stjude/XenoCP/assets/116059475/18080eb4-d83b-49f9-8c82-18cf7c1fc1c0">


Is the contamination rate calculated as:

Contamination Rate = （702−572）/ 702
 
Thank you for your clarification.
