### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by zhaowsong** [stjude/XenoCP#48]
Hello authors,

I have been working with xenocp on the supercomputing cluster, concurrently running whole-genome sequencing (WGS) for two samples with BAM files. I've noticed that every time I address one issue, another one seems to emerge. I've invested two weeks in troubleshooting this software......

![Uploading image.png…]()

**Comment by adthrasher** [comment]
Unfortunately, your image attachment did not come through. On many HPC systems, the `/tmp` directory on a node is quite small. `cwltool` users `/tmp` in the container for its intermediate working directories. By default, `singularity` mounts uses `/tmp` on the host to store `/tmp` in the container. For our HPC system, this will often run out of storage space. Yours may be the same. To get around this, you can use the `-W` / `--workdir` option to Singularity with a directory that has sufficient available space.

Since XenoCP works by splitting the original BAM, converting to FastQ, aligning to the contaminant genome, and then producing a cleaned BAM, you may need available storage that is several multiples of the original BAM size.

**Comment by zhaowsong** [comment]
Hello adthrasher,

Below is my code, and I have specified the working directory, but in the log file, it seems to still default to the './tmp' directory.....

<img width="643" alt="image" src="https://github.com/stjude/XenoCP/assets/116059475/5c746a34-b017-4ba3-8f96-baa71965cb5a">

<img width="680" alt="image" src="https://github.com/stjude/XenoCP/assets/116059475/023ca31a-5a9a-4154-ac3f-4387c5bbc455">

**Comment by zhaowsong** [comment]
I don't know if this software is specifically designed for use on the St. Jude Cloud platform. If it is, the documentation should clearly state this. At the very least, this has been the most challenging software installation and usage experience I've encountered on an HPC platform.

**Comment by zhaowsong** [comment]
same error 

<img width="798" alt="image" src="https://github.com/stjude/XenoCP/assets/116059475/3567bce6-5ec9-48f1-a647-64d359385228">

**Comment by mcrusch** [comment]
> I don't know if this software is specifically designed for use on the St. Jude Cloud platform.

In its original design, it was run on an HPC without containerization.  Since then, we have added Docker support and released it in St. Jude Cloud.

Extending this to Singularity is a logical next step, and we're happy to work with you to get it working using Singularity.  We will be updating the README as we go along to make it easier for the next Singularity user.

> Below is my code, and I have specified the working directory, but in the log file, it seems to still default to the './tmp' directory.....

Thanks for sending that.  I am not a Singularity expert, but it appears that by default Singularity exposes the entire host filesystem in the running container, so -W is effectively ignored.  I would recommend adding --containall to your singularity call to hide the host FS.  This should cause it to honor -W.  Note that the messages generated by XenoCP will still reference /tmp because that is the path inside the container.  However with --containall and -W, /tmp inside the container will map to your -W dir on the host system.

**Comment by mcrusch** [comment]
The README now contains information for running in Singularity, including the command-line arguments that will redirect /tmp to an appropriate location of your choice.  I believe that should address this issue, so I'm going to close it.  If you run into problems, feel free to reopen.
